unicef/inventory

.circleci/config.yml
.circleci/deploy.sh
.gitignore
.gitlab-ci.yml

This commit uses an existing GitHub Action to build and deploy a Hugo site to GitHub Pages. Let's see if it works.

ci: Migrate from GitLab CI to Circle CI

---

.circleci/config.yml

The CI environment deploys from Ubuntu 18.04. I was using the Alpine
package manager, `apk`, but of course it is not installed. This should
fix this issue.
I have to merge this change to `main` to evaluate whether it will deploy
the site or not.

ci: Use apt, not apk, in deploy step

---

config.toml

The social links were pointing towards @jwflory's social accounts This
change switches them to point toward's unicef's github and twitter

:wrench: switch social links to use unicef

---

.circleci/config.yml

Added in CircleCI-Public/hugo-orb#45 and CircleCI-Public/hugo-orb#46.
This commit turns HTML Proofer back on. Previously, it failed because of
unexpected error codes from sites linked elsewhere. This uses the new
feature flags added upstream in an effort to hopefully gain the helpful
feedback of when links in the site are broken.

ci: Enable htmlproofer checks on new Pull Requests

---

content/meta/overview.en.adoc

This commit adds a first draft of the structure of the UNICEF Open
Source Mentorship programmed offered in the UNICEF Ventures team.
Eligibility is the only defined criteria of the document so far, but a
12-month roadmap of common milestones and achievements will be added in
future commits.

meta: Initial commit, structure overview of O.S. Mentorship

---

.github/ISSUE_TEMPLATE/01-bug.md
.github/ISSUE_TEMPLATE/02-improvement.md
.github/ISSUE_TEMPLATE/03-new.md
.github/ISSUE_TEMPLATE/04-content.md

I added four new issue templates:
1. Bug reports
2. Improvements for existing functionality
3. New features and ideas
4. Content improvements, suggestions, and corrections
I realized there were not any issue templates, and this makes it hard
for me to structure my own thoughts when reviewing requirements for
upcoming work.

meta: Add four issue templates

---

.gitmodules
config.toml

This commit updates the UNICEF Open Source Inventory to use a new git
submodule for the Hugo theme. The new submodule comes from a forked
repository of the original Dot theme used in the project.
In the future clones and CI pipelines, it should use the new theme. This
allows us to test new changes made to the theme locally from this Hugo
site (without deploying a new version to production to test).
Closes #13.
CC: @Idadelveloper, this will un-block issue #14 so it can be worked on.

theme: Update git submodule to forked theme (closes #13)

---

.github/CONTRIBUTING.md
README.md

This commit adds new contributing guidelines. The contributing
guidelines also provide an explanation of cloning the repository with
the necessary git submodule. This should avoid future headaches for
anyone who works with or contributes to this repository.
Also added a note on installing AsciiDoctor, thanks to @Idadelveloper
pointing out the undocumented dependency for the project.
Closes #17.

Add contributing guidelines, better docs (closes #17)

---

content/documentation/hall-of-fame.en.adoc

This commit adds a new entry for the @google MediaPipe documentation
into the existing Documentation Hall of Fame:
https://google.github.io/mediapipe/
It was shared with me by current @unicef Innovation Fund grantee
@Wonder-Tree. Props to @musab1234 and @usmankaiz for sharing this one in
an Open Source Mentorship programme call.

docs: Add @google MediaPipe documentation to Hall of Fame

---

.gitmodules

Somehow I forgot to update the submodule URL in PR #16, even though I
changed the other submodule metadata. Sometimes this stuff can be weird.
Props to @Idadelveloper for pointing this one out.

git: Use updated submodule for forked repo theme

---

content/data/traps.en.adoc

This commit adds an attribution to the "Fairness and Abstraction in
Sociotechnical Systems" paper published at the 2019 ACM Conference on
Fairness, Accountability, and Transparency. The information on this
Inventory page is a summary of this research report.
Closes #10.

data: Add citation for AI Traps article (closes #10)

---

content/meta/workflow-metrics.en.adoc

This commit adds a first publication of a new type of meta page to
document the process of how I generally collect metrics. It is very
rough, but the idea is this is something that can be built on and
expanded over time.

meta: Document workflow for capturing analytic data

---

content/meta/workplan-bridge-funding.en.adoc

This commit adds the Open Source workplan requirements for the incoming
Bridge Funding cohort to the Open Source Inventory. The current format
is text-heavy and crude, but there is potential to model this into
another feature in the site theme later on.

meta: Add Bridge Funding cohort workplan notes

---

config.toml
content/meta/maintainers-guide.en.adoc
syntax.css

In order to see results, follow this syntax making sure you state the name of the language immediately after the `highlight` opening shortcode. This example uses the Go programming language. In between the opening and closing `highlight` shortcode is where the actual code will reside.
```
{{< highlight go "linenos=table,hl_lines=8 15-17,linenostart=199" >}}
// ... code
{{< / highlight >}}
```

Add code syntax highlighting to code blocks #39

---

content/meta/create-new-category.en.adoc
content/meta/maintainers-guide.en.adoc
content/meta/modules.en.adoc

This commit adds a new how-to page that describes how to add a new
category to the Open Source Inventory. This came up while I was working
on Pull Request #52 when I forgot the link to the icon set… so better to
document it for next time.

meta: Document how to create Inventory categories

---

.circleci/config.yml

This commit fixes the CircleCI pipeline by using a read-write deploy key
for checking out changes from the unicef/inventory repository, and
subsequently pushing the changes back into the `gh-pages` branch when
the `deploy` job successfully completes.
This is necessary because I had previously used a user key tied to my
individual GitHub account, and this key was reset when I reauthenticated
my CircleCI account to GitHub while debugging an unrelated issue with
CircleCI support. This approach, while less intuitive, is more
sustainable so that the deploy key is not bound to my personal GitHub
account.
https://circleci.com/docs/2.0/gh-bb-integration/#creating-a-github-deploy-key

ci: Fix builds with a repo-specific deploy key

---

config.toml
content/dev-tools/continuous-integration.en.adoc
content/governance/governance.en.adoc
content/hardware/intro.en.adoc
content/legal-policy/contributor-license-agreement-cla.en.adoc
content/legal-policy/gpl-comparison.en.adoc
content/meta/create-new-category.en.adoc
content/meta/maintainers-guide.en.adoc
content/meta/modules.en.adoc
content/meta/workplan-bridge-funding.en.adoc
content/missions/codes-of-conduct.en.adoc
content/project-management/project-boards.en.adoc

This fixes issue #29. By default hugo turns off the asciidoc automatic TOC since it has its own TOC.
Setting preserveTOC to 'true' instead of 'false' turns on asciidoc's TOC.
Signed-off-by: Ida Delphine <mida@unicef.org>

Add asciidoc config for automatic TOC

---

content/meta/create-new-mission.en.adoc
content/missions/_template.en.adoc

This commit adds a draft page of a template that can be reused for
creating new Missions in the future. It also adds documentation as a new
Meta page to describe writing new Missions for other content authors.
This is contributing work to #51. I realized that Missions were not
written in a common format, and this disrupts the user experience. Using
a common template and documenting it also reduces bus factor to include
other writers in the process.

missions: Create a template for writing new Missions

---

content/missions/charters.en.adoc
content/missions/codes-of-conduct.en.adoc
content/missions/good-first-issue.en.adoc

This commit adds a new Mission for Project Charters. It provides a
blueprint for what goes into defining a charter in an Open Source
context. This resource is drafted in support of the incoming August 2021
cohort in the UNICEF Innovation Fund.
Closes #51.

missions: Add a Project Charter Mission (closes #51)

---

content/design/reading-list.en.adoc

This commit adds the Ushahidi Open Design work, maintained by
@Erioldoesdesign, into the Design & UX Reading List in the Design
category. It has a good collection of resources and guided content that
we can amplify in the reading list.
Closes #3.

design: Add Ushahidi Open Design (closes #3)

---

content/meta/mentorship/_index.en.adoc
content/meta/mentorship/modules.en.adoc
content/meta/mentorship/needs-assessment-template.en.adoc
content/meta/mentorship/overview.en.adoc
content/meta/mentorship/templates.en.adoc
content/meta/mentorship/workplan-bridge-funding.en.adoc

This commit improves the general overview and layout of the Meta
category to include a new sub-section specifically for the Open Source
Mentorship programme. This makes it easier to group like content
together, and opens up possibility for more sub-categories in the Meta
category in the future.
This commit precedes a change to add a new page about on-boarding for
the Open Source Mentorship programme. ( #36 )

meta: Create new Mentorship sub-section

---

content/meta/inventory/_index.en.adoc
content/meta/inventory/create-new-category.en.adoc
content/meta/inventory/create-new-mission.en.adoc
content/meta/inventory/maintainers-guide.en.adoc

This commit creates a new sub-section for the Open Source Inventory site
underneath the Meta category. This follows on to the change introduced
in #70 to make it easier to navigate content in this category, as the
amount of content continues to grow.
It also gives us more design context for #61.

meta: Create new Inventory sub-section

---

content/meta/mentorship/onboarding.en.adoc

This commit adds an on-boarding guide, or the Terms of Reference, for
new inductees to the UNICEF Open Source Mentorship programme. It is
adapted from the Terms of Reference document, originally drafted in a
Google Doc. This takes that Terms of Reference document, converts it to
AsciiDoc, and better integrates it into existing Inventory content.
https://docs.google.com/document/d/1U_YnIx7Oe1D5O5sBN9FmI2GaC8D93P972v8jcs63EHQ/edit?usp=sharing
There is more content to add here, but for now, this is a good first
step. The Google Doc will be wiped out and replaced with a link out to
this page once it is published.
Closes #36.

meta: Add On-boarding guide (closes #36)

---

content/announcements/circleci-orbs.en.adoc

This commit adds a new announcement to the Inventory site about using
CircleCI Orbs. The call-out links to a post on the Venture Fund forum
about using four Orbs to enhance or improve any CI pipeline built using
CircleCI.

:mega: :newspaper: announcements: Add call-out to CircleCI Orbs post

---

content/legal-policy/trademark.en.adoc

This commit adds a new page to the "Legal & Policy" category titled,
"Trademark strategies". It includes an introduction to what trademarks
are, why they matter in an Open Source context, and it gives a specific
case study of the Moodle learning management system as a model for
trademark management and business model integration.
The purpose of this page is to provide guidance and nonbinding advice to
UNICEF Venture Fund companies in defining their own trademarks and
crafting a strategy around the management of project marks. This
compliments other content on defining project charters and governance.
Closes #49.

:new: :tm: legal-policy: Add trademark strategy overview (closes #49)

---

.circleci/config.yml

This commit adds a new CircleCI job that cleans and beautifies the HTML
before it goes to the deployment job. This makes HTML on the production
site in GitHub Pages easier for humans to inspect and read.

:alembic: :sparkles: ci: Add html-tidy job for publishing clean HTML

---

content/legal-policy/creative-commons.en.adoc

This commit creates a new page that introduces the Creative Commons
license family in a UNICEF context. It introduces the licenses, explains
the difference between our preferred Free Cultural licenses and other
Creative Commons license variants, and gives the reader clarification on
how to learn more about the licenses.
This can serve as a common, public reference point for the licenses we
permit, and maybe more importantly, why.

:judge: :telescope: legal-policy: Add Creative Commons primer

---

content/dev-tools/continuous-integration.en.adoc

* TravisCI has changed their business model, moving all users from
travis-ci.org to travis-ci.com. With a limited number of build
minutes per month.
* Updated the references to `.travis-ci.yml` files, in favor of
CircleCI, GitLab, GitHub Action configurations
* Propose SemaphoreCI as they provide free unlimited build minutes for
Open Source public repositories
From their website:
> Can I use Semaphore for my open source project?
>
> Our Open Source plan allows unlimited build minutes for building
> your public repositories completely free of charge, with 4
> e1-standard-2 machines and 1 a1-standard-4 machine at your disposal.
> - https://semaphoreci.com/pricing
Closes #96

Remove TravisCI from proposed CI platforms - Propose SemaphoreCI

---

config.toml

Beginning from Hugo v0.91.0 and on, security hardening was added to the
Hugo build runtime. This affects how Hugo calls Asciidoctor to generate
HTML from Asciidoc source. Without this setting, `asciidoctor` will fail
to run in Hugo v0.91.0 or later, and cause any pipelines without this
configuration to fail.
More info: https://github.com/gohugoio/hugo/releases/tag/v0.91.0

:lock: config: Add `^asciidoctor$` to new security configuration

---

layouts/partials/cohorts.html

@jwflory this addresses #98 
I noticed the cards were overlapping on smaller screens.
The second commit fixes the issue.
.

Wrap text description of profile cards around logo

---

content/meta/inventory/_index.en.adoc
content/meta/mentorship/_index.en.adoc

Closes unicef/inventory-hugo-theme#32.
This commit removes `type: docs` from the sub-category index pages in
the Meta category. This prevents them from appearing in their own card
on the index page view. They still render as expected within the sub-
category.
Nice catch @Idadelveloper.

:memo: :boom: meta: Hide sub-categories from index page

---

.github/CODE_OF_CONDUCT.adoc

This commit upgrades the Code of Conduct, taken from the Contributor
Covenant, from version 2.0 to 2.1. This includes minor changes to the
community statement around race and color.
I also updated contact information to distinguish the contact point as
for the UNICEF Office of Global Innovation and not UNICEF globally. I
also edited "Innovation Fund" to "Venture Fund" per upcoming changes to
the fund's branding.

:memo: :arrow_up: Code of Conduct: Upgrade to CC v2.1, update contact

---

content/cohorts/blockchain/rumsan.en.adoc

This commit adds the Rumsan/Rahat Discord server to the team profile for
Rumsan. It will appear as a place to engage and ask questions towards
the bottom of the profile.
CC: @rakimsth

:speech_balloon: :link: cohorts: Add Discord link for Rumsan/Rahat

---

layouts/partials/cohorts.html
layouts/partials/types.html

@jwflory this addresses [#27](https://github.com/unicef/inventory-hugo-theme/issues/27)
It looks like this:

Improve user experience of Cohorts sidebar navigation

---

content/meta/inventory/intern-guide.en.adoc

This commit adds an intern on-boarding guide to help future interns get
up to speed with the Open Source Inventory and how things are set up.
@Idadelveloper wrote this in the final week of her internship, and we
will continue to use this as the preferred way to bring on new
contributors who might work on the project for longer than 1-2 months.
ref: https://docs.google.com/document/d/1eDh2QLJ-Iwz_ELGn9oIj4MvtqC1iMIFPbGro0K52zVE/edit?usp=sharing

:new: :memo: meta: Add intern on-boarding guide from @Idadelveloper

---

config.toml

This commit adds a new drop-down menu to the Open Source Inventory. The
_Toolkits_ drop-down includes links to @dalvarez83's Data Science & A.I.
Toolkit and @iperdomo's Software Development Toolkit. This change can be
mirrored to all other toolkit sites as well to improve discoverability.
This should be merged once both sites begin to publish new content.

:wrench: config: Add Toolkits menu, link out to DS and SD toolkits

---

.github/ISSUE_TEMPLATE/config.yml
README.md
config.toml
content/announcements/_index.en.adoc
content/cohorts/_index.en.adoc
content/cohorts/others/_index.en.adoc
content/cohorts/vr-ar/_index.en.adoc
content/communities/fedora.en.adoc
content/communities/public-lab.en.adoc
content/legal-policy/trademark.en.adoc
content/meta/inventory/intern-guide.en.adoc
content/meta/inventory/maintainers-guide.en.adoc
content/meta/mentorship/modules.en.adoc
content/meta/mentorship/needs-assessment-template.en.adoc
content/meta/mentorship/onboarding.en.adoc
content/meta/mentorship/overview.en.adoc
content/meta/mentorship/workplan-bridge-funding.en.adoc
content/meta/workflow-metrics.en.adoc
layouts/partials/types.html

This follows guidance shared by Mara Navarro on branding best practices
for the Venture Fund. We standardize our name as Venture Fund given the
new possibility of other funding modalities that may emerge in the
coming future.

:truck: :pencil2: Branding: Change "Innovation Fund" to "Venture Fund"

---

content/cohorts/ds-ai/ottaa-project.en.adoc

This commit adds the Facebook and Instagram information for the OTTAA
Project into the team profile they have on the Open Source Inventory
website. This also updates the theme submodule to the latest commit that
incorporates the new social media platforms.
Related to unicef/inventory-hugo-theme#130.

:memo: cohorts: Add Facebook and Instagram to OTTAA Project profile

---

content/missions/charters.en.adoc

This commit revises the "Charters" mission to include these changes:
* **Add Talk2U vision, mission, and community statements as an example**
in the "Take-off! Time to launch" section. The community statement is
an especially useful example with clear ties between contributors and
the activities they lead.
* **Add keywords** to improve discoverability in site search bar.
* **Add new tags** to better describe the topic areas of a charter.
The motivation for this edit comes from conversations with the most
recently incoming Venture Fund cohort (AI/DS 2022) and the example I
keep showing from Talk2U. It keeps things together in one place!
CC: @siddharthvipul

:memo: missions: Add Talk2U example to project charter how-to

---

content/_index.en.md

This commit creates an `_index.en.md` file in the `content/` directory, therefore giving the UNICEF Open Source Inventory an explainer text in-between the search bar and the content category boxes.
Closes unicef/inventory-hugo-theme#154.

:memo: index: Add site description to site index page
